name: Main 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check:
    name: Run Checks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Load files
      run: |
         cat files/setup.md | sed -n '/^```/,/^```/ p' | sed '/^```/d' > files/setup.sh
         cat files/xps13-9343.md | sed -n '/^```/,/^```/ p' | sed '/^```/d' > files/xps13-9343.sh
         sed -i '1s|^|#!/usr/bin/env bash\n|' files/setup.sh
         sed -i '1s|^|#!/usr/bin/env bash\n|' files/xps13-9343.sh

    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      with:
        severity: error
        scandir: './files'
      env:
        SHELLCHECK_OPTS: -s bash

  dist:
    name: Create Distribution
    runs-on: ubuntu-latest
    needs: check
    steps:
      - uses: actions/checkout@v2

      - name: Download Gatsh 🧶
        run: wget https://raw.githubusercontent.com/hschne/gatsh/master/gatsh && chmod +x gatsh

      - name: Build Dist
        run: ./gatsh setup.sh > dist/setup.sh

      - name: Commit Updated Files 📤
        uses: EndBug/add-and-commit@v7
        with:
          add: "['dist/setup.sh']"
          message: "Update dist"
